### ISSUE TITLE
Player scope 구현

### ISSUE THREAD

**Issue by blackdurumi** [hoonww/WaterColor_Dream_by_hoonww#4]
예상 낙하 위치 보여주기

**Comment by YangHun** [comment]
1. 회전 인풋이 들어오거나 플레이어가 이동할때마다 scope도 같이 이동하면서 다음에 착지할것같은부분을 보여줌

2. scope 바로 아래 타일의 색을 실시간으로 가져와서, 플레이어가 그 색에 닿았을 경우 바뀔 것으로 예상되는 색을 ui로 표시
